stats: disable matplotlib use of a xwindows backend
When generating statistics for a system which does not have a DISPLAY
configured/installed, the request may fail with the following error:

    _tkinter.TclError: no display name and no $DISPLAY environment variable

Disabling the backend configuration for matplotlib as it is not required
for generated statistics.

Signed-off-by: James Knight <james.d.knight@live.com>